### ISSUE TITLE
ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by bayeslearner** [blgm/jfq#419]
ENAMETOOLONG: name too long, stat '(**.snapshot_groupSnapshotChildren).*@$g[$g.entitySnapshot_properties._class="SubGroup" ]
.($g.snapshot_monitorSnapshotChildren).*.(
    
    {
        "group": $g.entitySnapshot_properties._name,
        "name":  entitySnapshot_properties._name,
        "xxx": 1;
    }
)'

I tried this here https://try.jsonata.org/ and it works fine.

**Comment by bayeslearner** [comment]
solved  by using file for query

**Comment by blgm** [comment]
Thank you for raising this @bayeslearner and for finding a work-around!

I think the issue is that the first argument to `jfq` can be a JSONata query, or it can be a file name. So `jfq` checks to see if a file of that name exists. But it seems that when the first argument is too long, something complains that the file name is invalid. The solution is probably to do a file name validity check as well.

Code here: https://github.com/blgm/jfq/blob/3223ffce22e127b46c195ea40727bbb437e504fd/src/getopts.js#L31
